### ISSUE TITLE
Power management in High Sierra

### ISSUE THREAD

**Issue by kamyar1979** [RehabMan/OS-X-Generic-USB3#11]
I was using this package for months in Sierra with no problem. After upgrading to High Sierra, Shutdown caused the system restart and sleep did not wake. After so much searching and try and error I found out that by removing this kext, shutdown and sleep both fixes! This good old library has power management issues with High Sierra  (At least 10.13.4+). I am using an NEC (renessas) USB3 PCI-e card on Gigabyte SandyBridge mainboard.

**Comment by RehabMan** [comment]
Unfortunately, no one is really using this kext anymore... (we all have since updated our hardware such that we have supported xHCI controllers).

As a result, no one is interested in fixing anything in it...

**Comment by kamyar1979** [comment]
Ok, I am choosing some good NVMe support, ECC, DDR4 mainboard to upgrade. But till then, at least give me some clues for patching your kext or some boot arguments (like gux-*) to resolve the problem temporaily.

**Comment by RehabMan** [comment]
Full source is available here.  Up to you to fix it if you want to use it.

I don't know why you would use a NEC/Renasas card when you could simply use a card that has native support (FL1100).
