### ISSUE TITLE
Resume from sleep

### ISSUE THREAD

**Issue by jief666** [RehabMan/OS-X-Generic-USB3#12]
This driver works perfectly fine on 10.13.6 on my Lenovo x220, except for one little thing : the connected hard drive is disconnect and reconnected at wake.

The USB controller, on this laptop is the NEC Renesas uPD720200. Is there a way to have resume from sleep to work ? Should I use a patched AppleXHCI kext instead of GenericUSBXHCI.kext ?

Any idea ?
Thanks.

**Comment by RehabMan** [comment]
Unfortunately, no one is working on this kext anymore.
