### ISSUE TITLE
Problem with shutdown

### ISSUE THREAD

**Issue by rafaelmaeuer** [RehabMan/OS-X-Generic-USB3#13]
Im glad this kext enables the USB3 ports on my ASUS P8P67 Pro Rev3.0 so a big thank you first. No other kext or solution I tried was able to do this and regarding the answer in this blog no other solution will do: [Link](https://www.hackintosh-forum.de/forum/thread/28914-anleitung-usb-3-0-el-capitan-high-sierra-mojave-f%C3%BCr-jedermann-zukunftssicher-f%C3%BCr/?postID=460279#post460279). 
But when I add the kext, the system doesn't shutdown anymore, it just waits and then restarts. I had this problem earlier and I was able to fix it by disabling the "FixShutdown" ACPI patch. I already tried to re-enable it but without success. Im running OS X Mojave.

**Comment by RehabMan** [comment]
No one is maintaining this kext.  Suggest you ignore/disable any unsupported USB3 controller and install a supported USB3 card (FL1100 based).

**Comment by rafaelmaeuer** [comment]
Ok thats very sad, because the kext works basically perfekt except this issue. Before giving up and spending money for a FL1100 based card I want to know if you know any possibility of finding out what causes the system to reboot? Are there any logs (except verbose boot) that can be enabled for further investigation?
