### ISSUE TITLE
Problem on Asmedia 1042 USB 3.0 Controller

### ISSUE THREAD

**Issue by sloeberGJ** [RehabMan/OS-X-Generic-USB3#2]
USB 3.0 only works if i insert the USB device before my laptop is powered up. It has to be attached when my pc is booting up. Otherwise it gives this error: "32,000 kernel[0]: USBF: 3.168 GenericUSBXHCI::CreateRootHubDevice Bus 14 already taken"

Laptop: Asus K53SV
CPU: Intel Core i5 2430M
USB 3.0 Controller: Asmedia  1042

Link to tonymacx86 thread: http://www.tonymacx86.com/general-help/148333-genericusbxhci-kext-yosemite.html

**Comment by RehabMan** [comment]
This kext has issues on Yosemite.  Best to use (patched) AppleUSBXHCI instead.

**Comment by gobetti** [comment]
I second this issue on El Capitan 10.11.2 with GenericUSBXHCI 1.2.11, except that no error is presented in the system log.
