### ISSUE TITLE
Yosemite

### ISSUE THREAD

**Issue by Dawn13** [RehabMan/OS-X-Generic-USB3#3]
Is it possible to make it work with yosemite ? The driver gets loaded and i can see it in "about this mac", but attached devices don't connect.

**Comment by RehabMan** [comment]
It is best to use AppleUSBXHCI.kext.  This kext has issues on Yosemite, not likely to be fixed unless someone knowledgeable looks at it.  I'm now using AppleUSBXHCI on all my hacks... Zenith432 has said he really doesn't have the time to figure it out.
