### ISSUE TITLE
System halts before shutting down, restarting, and sleeping

### ISSUE THREAD

**Issue by rossistboss** [RehabMan/OS-X-Generic-USB3#4]
Background: I was having an issue with my hackintosh where the system halted before shutdown/restart/sleep. The system halted for 10-20 seconds. It only halted when I had my mouse and/or keyboard plugged in. 

After removing the kext, I did not have this problem. The issue persisted even after compiling the latest sources from this repo. 

[This /r/hackintosh post has more information](http://www.reddit.com/r/hackintosh/comments/2ul4t5/gaz87mxd3h_hangs_before_shutdownrestartsleep/). 

Various system information (If you need more ask me!):

OS X 10.10.2
GA-Z87MX-D3H

Keyboard: Microsoft Sidewinder X4
Mouse: Gigabyte M6880

There is no halt when both the mouse and keyboard aren't plugged in. If either one is plugged in, then there is a halt. For this reason I doubt it is an issue caused by either one of them. 

Please look into this issue RehabMan

Thank you!

**Comment by RehabMan** [comment]
This kext has issues on Yosemite.  It is not recommended for use with Yosemite (best to use AppleUSBXHCI.kext instead).  If you do plan to use it, make sure you're using the current version that is built for Yosemite.
