### ISSUE TITLE
KP with El Capitan

### ISSUE THREAD

**Issue by Polishapple** [RehabMan/OS-X-Generic-USB3#5]
Hi, kext not working under 10.11 (Gets Kernel Panic on boot). USB 3.0 Controller - NEC upd720202 on expresscard slot

**Comment by RehabMan** [comment]
Not likely to be fixed.  There have been problems with GenericUSBXHCI.kext since Yosemite.  No one is interested in fixing it as it is usually possible to get the native kexts to work.

**Comment by RehabMan** [comment]
Closing won't fix.
