### ISSUE TITLE
Audio Stopped after installing

### ISSUE THREAD

**Issue by RonCan** [RehabMan/OS-X-Generic-USB3#6]
Hi RehabMan. With this my NEC USB3 started working, all the ports. But it caused one problem.Now my Intel HD Audio which I made to work by using VoodooHDA.kext stopped working. Is it a know problem? Is there any solution? If all else doesn't work I'd like to get my Audio back at the cost of losing USB3, I'll be happy to provide any information

**Comment by RehabMan** [comment]
This kext has nothing to do with VoodooHDA.kext.

**Comment by RonCan** [comment]
But my audio works perfectly fine until I install this kext, after which my
USB ports start working including usb 3 ones and audio stops working

**Comment by RehabMan** [comment]
This is not the appropriate place to discover your mistake.
