### ISSUE TITLE
Kext don't work in my computer

### ISSUE THREAD

**Issue by jarden-liu** [RehabMan/OS-X-Generic-USB3#7]
![qq20170210-0](https://cloud.githubusercontent.com/assets/11712343/22814284/353d26d4-ef8d-11e6-95f5-489d9c908c19.jpg)
I tried Generic-USB3 and USB-Inject-All,but all in vain。
how can i do to fix it？

**Comment by RehabMan** [comment]
Your problem has nothing to do with GenericUSBXHCI.kext.

Follow the Clover guide linked from the FAQ.

http://www.tonymacx86.com/el-capitan-laptop-support/164990-faq-read-first-laptop-frequent-questions.html
