### ISSUE TITLE
Asmedia  1042 on Sierra

### ISSUE THREAD

**Issue by xXcodgerXx** [RehabMan/OS-X-Generic-USB3#8]
Hello,

There seems to be an issue with the Asmedia 1042 USB 3.0 controller.
The ports work if - 1) There is a device plugged into them at boot up. - or - 2) I am already booted, I plug something in (nothing) I unplug and plug it back in. It shows up. 

I see on older osx versions someone reported a similar issue and it was closed out.

Thanks.

**Comment by RehabMan** [comment]
It is a known problem with this kext.
won't fix.
Most people just install compatible FL1100 based hardware...
