### ISSUE TITLE
Small Question

### ISSUE THREAD

**Issue by Niresh12495** [RehabMan/OS-X-Generic-USB3#9]
Actually do you mean that this will not work in Sierra?

https://github.com/RehabMan/OS-X-Generic-USB3/commit/461165bb273f9ddefe9b055dd809aa915f6c9464

**Comment by RehabMan** [comment]
For Intel hardware and a few others, it disables itself on 10.11 or later.
See here: https://github.com/RehabMan/OS-X-Generic-USB3/commit/c38eb13361129f7e255d10f379fcb079a9e6a7f5
